`define CLOCKFREQ = 100_000_000 // in Hz
parameter real clock_period = 1.0/CLOCKFREQ;
// time delays (in clock cycles)
`ifdef MODE0
	parameter int t_adl = 200 / clock_period; // minimum time => fastest (will be written forth as min)
	parameter int t_alh = 20  / clock_period; // min
	parameter int t_als = 50  / clock_period; // min
	parameter int t_ar  = 25  / clock_period; // min
	parameter int t_cea = 100 / clock_period; // max
	parameter int t_ch  = 20  / clock_period; // min
	parameter int t_chz = 100 / clock_period; // max
	parameter int t_clh = 20  / clock_period; // min
	parameter int t_clr = 20  / clock_period; // min
	parameter int t_cls = 50  / clock_period; // min
	parameter int t_coh = 0   / clock_period; // min
	parameter int t_cs= 70    / clock_period; // min
	parameter int t_dh= 20    / clock_period; // min
	parameter int t_ds= 40    / clock_period; // min
	parameter int t_ir= 10    / clock_period; // min
	parameter int t_rc = 100  / clock_period; // min
	parameter int t_rea = 40  / clock_period; // max
	parameter int t_reh= 30   / clock_period; // max
	parameter int t_rhoh = 0  / clock_period; // min
	parameter int t_rhw = 200 / clock_period; // min
	parameter int t_rhz= 200  / clock_period; // max
	parameter int t_rloh= 0   / clock_period; // min
	parameter int t_rp = 50   / clock_period; // min
	parameter int t_rr= 40    / clock_period; // min 
	parameter int t_wb= 200   / clock_period; // max
	parameter int t_wc= 100   / clock_period; // min
	parameter int t_wh=  30   / clock_period; // min
	parameter int t_whr= 120  / clock_period; // min
	parameter int t_wp= 50    / clock_period; // min
	parameter int t_ww = 100  / clock_period; // min
`elsif MODE1
	parameter int t_adl = 100 / clock_period; // min
	parameter int t_alh = 10  / clock_period; // min
	parameter int t_als = 25  / clock_period; // min
	parameter int t_ar  = 10  / clock_period; // min
	parameter int t_cea = 45  / clock_period; // max
	parameter int t_ch  = 10  / clock_period; // min
	parameter int t_chz = 50  / clock_period; // max
	parameter int t_clh = 10  / clock_period; // min
	parameter int t_clr = 10  / clock_period; // min
	parameter int t_cls = 25  / clock_period; // min
	parameter int t_coh = 15  / clock_period; // min
	parameter int t_cs= 35    / clock_period; // min
	parameter int t_dh= 10    / clock_period; // min
	parameter int t_ds= 20    / clock_period; // min
	parameter int t_ir=  0    / clock_period; // min
	parameter int t_rc = 50   / clock_period; // min
	parameter int t_rea = 30  / clock_period; // max
	parameter int t_reh= 15   / clock_period; // max
	parameter int t_rhoh = 15 / clock_period; // min
	parameter int t_rhw = 100 / clock_period; // min
	parameter int t_rhz= 100  / clock_period; // max
	parameter int t_rloh= 0   / clock_period; // min
	parameter int t_rp = 25   / clock_period; // min
	parameter int t_rr= 20    / clock_period; // min 
	parameter int t_wb= 100   / clock_period; // max
	parameter int t_wc=  45   / clock_period; // min
	parameter int t_wh=  15   / clock_period; // min
	parameter int t_whr=  80  / clock_period; // min
	parameter int t_wp= 25    / clock_period; // min
	parameter int t_ww= 100   / clock_period; // min
`elsif MODE2
	parameter int t_adl = 100 / clock_period; // min
	parameter int t_alh = 10  / clock_period; // min
	parameter int t_als = 15  / clock_period; // min
	parameter int t_ar  = 10  / clock_period; // min
	parameter int t_cea = 30  / clock_period; // max
	parameter int t_ch  = 10  / clock_period; // min
	parameter int t_chz = 50  / clock_period; // max
	parameter int t_clh = 10  / clock_period; // min
	parameter int t_clr = 10  / clock_period; // min
	parameter int t_cls = 15  / clock_period; // min
	parameter int t_coh = 15  / clock_period; // min
	parameter int t_cs= 25    / clock_period; // min
	parameter int t_dh= 5     / clock_period; // min
	parameter int t_ds= 15    / clock_period; // min
	parameter int t_ir=  0    / clock_period; // min
	parameter int t_rc = 35   / clock_period; // min
	parameter int t_rea = 25  / clock_period; // max
	parameter int t_reh= 15   / clock_period; // max
	parameter int t_rhoh = 15 / clock_period; // min
	parameter int t_rhw = 100 / clock_period; // min
	parameter int t_rhz= 100  / clock_period; // max
	parameter int t_rloh= 0   / clock_period; // min
	parameter int t_rp = 17   / clock_period; // min
	parameter int t_rr= 20    / clock_period; // min 
	parameter int t_wb= 100   / clock_period; // max
	parameter int t_wc=  35   / clock_period; // min
	parameter int t_wh=  15   / clock_period; // min
	parameter int t_whr=  80  / clock_period; // min
	parameter int t_wp= 17    / clock_period; // min
	parameter int t_ww= 100   / clock_period; // min
`elsif MODE3
	parameter int t_adl = 100 / clock_period; // min
	parameter int t_alh = 5   / clock_period; // min
	parameter int t_als = 10  / clock_period; // min
	parameter int t_ar  = 10  / clock_period; // min
	parameter int t_cea = 25  / clock_period; // max
	parameter int t_ch  = 5   / clock_period; // min
	parameter int t_chz = 50  / clock_period; // max
	parameter int t_clh = 5   / clock_period; // min
	parameter int t_clr = 10  / clock_period; // min
	parameter int t_cls = 10  / clock_period; // min
	parameter int t_coh = 15  / clock_period; // min
	parameter int t_cs= 25    / clock_period; // min
	parameter int t_dh= 5     / clock_period; // min
	parameter int t_ds= 10    / clock_period; // min
	parameter int t_ir=  0    / clock_period; // min
	parameter int t_rc = 30   / clock_period; // min
	parameter int t_rea = 20  / clock_period; // max
	parameter int t_reh= 10   / clock_period; // max
	parameter int t_rhoh = 15 / clock_period; // min
	parameter int t_rhw = 100 / clock_period; // min
	parameter int t_rhz= 100  / clock_period; // max
	parameter int t_rloh= 0   / clock_period; // min
	parameter int t_rp = 15   / clock_period; // min
	parameter int t_rr= 20    / clock_period; // min 
	parameter int t_wb= 100   / clock_period; // max
	parameter int t_wc=  30   / clock_period; // min
	parameter int t_wh=  10   / clock_period; // min
	parameter int t_whr=  80  / clock_period; // min
	parameter int t_wp= 15    / clock_period; // min
	parameter int t_ww= 100   / clock_period; // min
`elsif MODE4
	parameter int t_adl = 70  / clock_period; // min
	parameter int t_alh = 5   / clock_period; // min
	parameter int t_als = 10  / clock_period; // min
	parameter int t_ar  = 10  / clock_period; // min
	parameter int t_cea = 25  / clock_period; // max
	parameter int t_ch  = 5   / clock_period; // min
	parameter int t_chz = 30  / clock_period; // max
	parameter int t_clh = 5   / clock_period; // min
	parameter int t_clr = 10  / clock_period; // min
	parameter int t_cls = 10  / clock_period; // min
	parameter int t_coh = 15  / clock_period; // min
	parameter int t_cs= 20    / clock_period; // min
	parameter int t_dh= 5     / clock_period; // min
	parameter int t_ds= 10    / clock_period; // min
	parameter int t_ir=  0    / clock_period; // min
	parameter int t_rc = 25   / clock_period; // min
	parameter int t_rea = 20  / clock_period; // max
	parameter int t_reh= 10   / clock_period; // max
	parameter int t_rhoh = 15 / clock_period; // min
	parameter int t_rhw = 100 / clock_period; // min
	parameter int t_rhz= 100  / clock_period; // max
	parameter int t_rloh= 5   / clock_period; // min
	parameter int t_rp = 12   / clock_period; // min
	parameter int t_rr= 20    / clock_period; // min 
	parameter int t_wb= 100   / clock_period; // max
	parameter int t_wc=  25   / clock_period; // min
	parameter int t_wh=  10   / clock_period; // min
	parameter int t_whr=  80  / clock_period; // min
	parameter int t_wp= 12    / clock_period; // min
	parameter int t_ww= 100   / clock_period; // min
`elsif MODE5
	parameter int t_adl = 70  / clock_period; // min
	parameter int t_alh = 5   / clock_period; // min
	parameter int t_als = 10  / clock_period; // min
	parameter int t_ar  = 10  / clock_period; // min
	parameter int t_cea = 25  / clock_period; // max
	parameter int t_ch  = 5   / clock_period; // min
	parameter int t_chz = 30  / clock_period; // max
	parameter int t_clh = 5   / clock_period; // min
	parameter int t_clr = 10  / clock_period; // min
	parameter int t_cls = 10  / clock_period; // min
	parameter int t_coh = 15  / clock_period; // min
	parameter int t_cs= 15    / clock_period; // min
	parameter int t_dh= 5     / clock_period; // min
	parameter int t_ds= 7     / clock_period; // min
	parameter int t_ir=  0    / clock_period; // min
	parameter int t_rc = 20   / clock_period; // min
	parameter int t_rea = 16  / clock_period; // max
	parameter int t_reh= 7    / clock_period; // max
	parameter int t_rhoh = 15 / clock_period; // min
	parameter int t_rhw = 100 / clock_period; // min
	parameter int t_rhz= 100  / clock_period; // max
	parameter int t_rloh= 5   / clock_period; // min
	parameter int t_rp = 10   / clock_period; // min
	parameter int t_rr= 20    / clock_period; // min 
	parameter int t_wb= 100   / clock_period; // max
	parameter int t_wc=  20   / clock_period; // min
	parameter int t_wh=  7    / clock_period; // min
	parameter int t_whr=  80  / clock_period; // min
	parameter int t_wp= 10    / clock_period; // min
	parameter int t_ww= 100   / clock_period; // min
`else
	`error "Compilation failed: Timing mode unspecified.\nRefer to Timing Modes."
`endif
